//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BiosigLibWin64 {

public enum B4C_ERROR {
  B4C_NO_ERROR = 0,
  B4C_FORMAT_UNKNOWN,
  B4C_FORMAT_UNSUPPORTED,
  B4C_CANNOT_OPEN_FILE,
  B4C_CANNOT_WRITE_FILE,
  B4C_CANNOT_APPEND_FILE,
  B4C_INSUFFICIENT_MEMORY,
  B4C_ENDIAN_PROBLEM,
  B4C_CRC_ERROR,
  B4C_DATATYPE_UNSUPPORTED,
  B4C_SCLOSE_FAILED,
  B4C_DECOMPRESSION_FAILED,
  B4C_MEMORY_ALLOCATION_FAILED,
  B4C_RAWDATA_COLLAPSING_FAILED,
  B4C_REREF_FAILED,
  B4C_INCOMPLETE_FILE,
  B4C_UNSPECIFIC_ERROR,
  B4C_CHAR_ENCODING_UNSUPPORTED
}

}
