//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BiosigLibWin64 {

class biosigPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="SWIGRegisterExceptionCallbacks_biosig")]
    public static extern void SWIGRegisterExceptionCallbacks_biosig(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_biosig")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_biosig(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_biosig(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_biosig(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="SWIGRegisterStringCallback_biosig")]
    public static extern void SWIGRegisterStringCallback_biosig(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_biosig(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static biosigPINVOKE() {
  }


  protected class SWIGWStringHelper {

    [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPWStr)]
    public delegate string SWIGWStringDelegate(global::System.IntPtr message);
    static SWIGWStringDelegate wstringDelegate = new SWIGWStringDelegate(CreateWString);

    [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="SWIGRegisterWStringCallback_biosig")]
    public static extern void SWIGRegisterWStringCallback_biosig(SWIGWStringDelegate wstringDelegate);

    static string CreateWString([global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPWStr)]global::System.IntPtr cString) {
      return global::System.Runtime.InteropServices.Marshal.PtrToStringUni(cString);
    }

    static SWIGWStringHelper() {
      SWIGRegisterWStringCallback_biosig(wstringDelegate);
    }
  }

  static protected SWIGWStringHelper swigWStringHelper = new SWIGWStringHelper();


  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_imaxdiv_t_quot_set")]
  public static extern void imaxdiv_t_quot_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_imaxdiv_t_quot_get")]
  public static extern long imaxdiv_t_quot_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_imaxdiv_t_rem_set")]
  public static extern void imaxdiv_t_rem_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_imaxdiv_t_rem_get")]
  public static extern long imaxdiv_t_rem_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_new_imaxdiv_t")]
  public static extern global::System.IntPtr new_imaxdiv_t();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_delete_imaxdiv_t")]
  public static extern void delete_imaxdiv_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_imaxabs")]
  public static extern long imaxabs(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_imaxdiv")]
  public static extern global::System.IntPtr imaxdiv(long jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_strtoimax")]
  public static extern long strtoimax(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_strtoumax")]
  public static extern ulong strtoumax(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_BIOSIG_VERSION_MAJOR_get")]
  public static extern int BIOSIG_VERSION_MAJOR_get();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_BIOSIG_VERSION_MINOR_get")]
  public static extern int BIOSIG_VERSION_MINOR_get();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_BIOSIG_PATCHLEVEL_get")]
  public static extern int BIOSIG_PATCHLEVEL_get();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_BIOSIG_VERSION_STEPPING_get")]
  public static extern int BIOSIG_VERSION_STEPPING_get();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_BIOSIG_VERSION_get")]
  public static extern int BIOSIG_VERSION_get();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_MAX_LENGTH_LABEL_get")]
  public static extern int MAX_LENGTH_LABEL_get();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_MAX_LENGTH_TRANSDUCER_get")]
  public static extern int MAX_LENGTH_TRANSDUCER_get();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_MAX_LENGTH_PID_get")]
  public static extern int MAX_LENGTH_PID_get();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_MAX_LENGTH_RID_get")]
  public static extern int MAX_LENGTH_RID_get();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_MAX_LENGTH_NAME_get")]
  public static extern int MAX_LENGTH_NAME_get();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_MAX_LENGTH_MANUF_get")]
  public static extern int MAX_LENGTH_MANUF_get();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_MAX_LENGTH_TECHNICIAN_get")]
  public static extern int MAX_LENGTH_TECHNICIAN_get();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_PhysMin_set")]
  public static extern void CHANNEL_TYPE_PhysMin_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_PhysMin_get")]
  public static extern double CHANNEL_TYPE_PhysMin_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_PhysMax_set")]
  public static extern void CHANNEL_TYPE_PhysMax_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_PhysMax_get")]
  public static extern double CHANNEL_TYPE_PhysMax_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_DigMin_set")]
  public static extern void CHANNEL_TYPE_DigMin_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_DigMin_get")]
  public static extern double CHANNEL_TYPE_DigMin_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_DigMax_set")]
  public static extern void CHANNEL_TYPE_DigMax_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_DigMax_get")]
  public static extern double CHANNEL_TYPE_DigMax_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_Cal_set")]
  public static extern void CHANNEL_TYPE_Cal_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_Cal_get")]
  public static extern double CHANNEL_TYPE_Cal_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_Off_set")]
  public static extern void CHANNEL_TYPE_Off_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_Off_get")]
  public static extern double CHANNEL_TYPE_Off_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_Label_set")]
  public static extern void CHANNEL_TYPE_Label_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_Label_get")]
  public static extern string CHANNEL_TYPE_Label_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_OnOff_set")]
  public static extern void CHANNEL_TYPE_OnOff_set(global::System.Runtime.InteropServices.HandleRef jarg1, char jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_OnOff_get")]
  public static extern char CHANNEL_TYPE_OnOff_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_LeadIdCode_set")]
  public static extern void CHANNEL_TYPE_LeadIdCode_set(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_LeadIdCode_get")]
  public static extern ushort CHANNEL_TYPE_LeadIdCode_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_Transducer_set")]
  public static extern void CHANNEL_TYPE_Transducer_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_Transducer_get")]
  public static extern string CHANNEL_TYPE_Transducer_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_PhysDimCode_set")]
  public static extern void CHANNEL_TYPE_PhysDimCode_set(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_PhysDimCode_get")]
  public static extern ushort CHANNEL_TYPE_PhysDimCode_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_TOffset_set")]
  public static extern void CHANNEL_TYPE_TOffset_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_TOffset_get")]
  public static extern float CHANNEL_TYPE_TOffset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_LowPass_set")]
  public static extern void CHANNEL_TYPE_LowPass_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_LowPass_get")]
  public static extern float CHANNEL_TYPE_LowPass_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_HighPass_set")]
  public static extern void CHANNEL_TYPE_HighPass_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_HighPass_get")]
  public static extern float CHANNEL_TYPE_HighPass_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_Notch_set")]
  public static extern void CHANNEL_TYPE_Notch_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_Notch_get")]
  public static extern float CHANNEL_TYPE_Notch_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_XYZ_set")]
  public static extern void CHANNEL_TYPE_XYZ_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_XYZ_get")]
  public static extern global::System.IntPtr CHANNEL_TYPE_XYZ_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_Impedance_set")]
  public static extern void CHANNEL_TYPE_Impedance_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_Impedance_get")]
  public static extern float CHANNEL_TYPE_Impedance_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_fZ_set")]
  public static extern void CHANNEL_TYPE_fZ_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_fZ_get")]
  public static extern float CHANNEL_TYPE_fZ_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_bufptr_set")]
  public static extern void CHANNEL_TYPE_bufptr_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_bufptr_get")]
  public static extern global::System.IntPtr CHANNEL_TYPE_bufptr_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_SPR_set")]
  public static extern void CHANNEL_TYPE_SPR_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_SPR_get")]
  public static extern uint CHANNEL_TYPE_SPR_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_bi_set")]
  public static extern void CHANNEL_TYPE_bi_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_bi_get")]
  public static extern uint CHANNEL_TYPE_bi_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_bi8_set")]
  public static extern void CHANNEL_TYPE_bi8_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_bi8_get")]
  public static extern uint CHANNEL_TYPE_bi8_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_GDFTYP_set")]
  public static extern void CHANNEL_TYPE_GDFTYP_set(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_CHANNEL_TYPE_GDFTYP_get")]
  public static extern ushort CHANNEL_TYPE_GDFTYP_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_new_CHANNEL_TYPE")]
  public static extern global::System.IntPtr new_CHANNEL_TYPE();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_delete_CHANNEL_TYPE")]
  public static extern void delete_CHANNEL_TYPE(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_FileName_set")]
  public static extern void HDRTYPE_FileName_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_FileName_get")]
  public static extern string HDRTYPE_FileName_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_VERSION_set")]
  public static extern void HDRTYPE_VERSION_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_VERSION_get")]
  public static extern float HDRTYPE_VERSION_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_Version_set")]
  public static extern void HDRTYPE_Version_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_Version_get")]
  public static extern float HDRTYPE_Version_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_TYPE_set")]
  public static extern void HDRTYPE_TYPE_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_TYPE_get")]
  public static extern int HDRTYPE_TYPE_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_Type_set")]
  public static extern void HDRTYPE_Type_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_Type_get")]
  public static extern int HDRTYPE_Type_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_data_get")]
  public static extern global::System.IntPtr HDRTYPE_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_IPaddr_set")]
  public static extern void HDRTYPE_IPaddr_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_IPaddr_get")]
  public static extern global::System.IntPtr HDRTYPE_IPaddr_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_SampleRate_set")]
  public static extern void HDRTYPE_SampleRate_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_SampleRate_get")]
  public static extern double HDRTYPE_SampleRate_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_NRec_set")]
  public static extern void HDRTYPE_NRec_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_NRec_get")]
  public static extern long HDRTYPE_NRec_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_T0_set")]
  public static extern void HDRTYPE_T0_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_T0_get")]
  public static extern long HDRTYPE_T0_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_HeadLen_set")]
  public static extern void HDRTYPE_HeadLen_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_HeadLen_get")]
  public static extern uint HDRTYPE_HeadLen_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_SPR_set")]
  public static extern void HDRTYPE_SPR_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_SPR_get")]
  public static extern uint HDRTYPE_SPR_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_LOC_set")]
  public static extern void HDRTYPE_LOC_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_LOC_get")]
  public static extern global::System.IntPtr HDRTYPE_LOC_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_NS_set")]
  public static extern void HDRTYPE_NS_set(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_NS_get")]
  public static extern ushort HDRTYPE_NS_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_tzmin_set")]
  public static extern void HDRTYPE_tzmin_set(global::System.Runtime.InteropServices.HandleRef jarg1, short jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_tzmin_get")]
  public static extern short HDRTYPE_tzmin_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_Calib_set")]
  public static extern void HDRTYPE_Calib_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_Calib_get")]
  public static extern global::System.IntPtr HDRTYPE_Calib_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_rerefCHANNEL_set")]
  public static extern void HDRTYPE_rerefCHANNEL_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_rerefCHANNEL_get")]
  public static extern global::System.IntPtr HDRTYPE_rerefCHANNEL_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_Patient_get")]
  public static extern global::System.IntPtr HDRTYPE_Patient_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_ID_get")]
  public static extern global::System.IntPtr HDRTYPE_ID_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_ELEC_get")]
  public static extern global::System.IntPtr HDRTYPE_ELEC_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_EVENT_get")]
  public static extern global::System.IntPtr HDRTYPE_EVENT_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_FLAG_get")]
  public static extern global::System.IntPtr HDRTYPE_FLAG_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_CHANNEL_set")]
  public static extern void HDRTYPE_CHANNEL_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_CHANNEL_get")]
  public static extern global::System.IntPtr HDRTYPE_CHANNEL_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_FILE_get")]
  public static extern global::System.IntPtr HDRTYPE_FILE_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_AS_get")]
  public static extern global::System.IntPtr HDRTYPE_AS_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_aECG_set")]
  public static extern void HDRTYPE_aECG_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_aECG_get")]
  public static extern global::System.IntPtr HDRTYPE_aECG_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_viewtime_set")]
  public static extern void HDRTYPE_viewtime_set(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_viewtime_get")]
  public static extern ulong HDRTYPE_viewtime_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDRTYPE_SCP_get")]
  public static extern global::System.IntPtr HDRTYPE_SCP_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_new_HDRTYPE")]
  public static extern global::System.IntPtr new_HDRTYPE();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_delete_HDRTYPE")]
  public static extern void delete_HDRTYPE(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section7_set")]
  public static extern void HDR_STRUCT_SCP_Section7_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section7_get")]
  public static extern global::System.IntPtr HDR_STRUCT_SCP_Section7_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section8_set")]
  public static extern void HDR_STRUCT_SCP_Section8_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section8_get")]
  public static extern global::System.IntPtr HDR_STRUCT_SCP_Section8_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section9_set")]
  public static extern void HDR_STRUCT_SCP_Section9_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section9_get")]
  public static extern global::System.IntPtr HDR_STRUCT_SCP_Section9_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section10_set")]
  public static extern void HDR_STRUCT_SCP_Section10_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section10_get")]
  public static extern global::System.IntPtr HDR_STRUCT_SCP_Section10_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section11_set")]
  public static extern void HDR_STRUCT_SCP_Section11_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section11_get")]
  public static extern global::System.IntPtr HDR_STRUCT_SCP_Section11_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section7Length_set")]
  public static extern void HDR_STRUCT_SCP_Section7Length_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section7Length_get")]
  public static extern uint HDR_STRUCT_SCP_Section7Length_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section8Length_set")]
  public static extern void HDR_STRUCT_SCP_Section8Length_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section8Length_get")]
  public static extern uint HDR_STRUCT_SCP_Section8Length_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section9Length_set")]
  public static extern void HDR_STRUCT_SCP_Section9Length_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section9Length_get")]
  public static extern uint HDR_STRUCT_SCP_Section9Length_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section10Length_set")]
  public static extern void HDR_STRUCT_SCP_Section10Length_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section10Length_get")]
  public static extern uint HDR_STRUCT_SCP_Section10Length_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section11Length_set")]
  public static extern void HDR_STRUCT_SCP_Section11Length_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_SCP_Section11Length_get")]
  public static extern uint HDR_STRUCT_SCP_Section11Length_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_new_HDR_STRUCT_SCP")]
  public static extern global::System.IntPtr new_HDR_STRUCT_SCP();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_delete_HDR_STRUCT_SCP")]
  public static extern void delete_HDR_STRUCT_SCP(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_B4C_ERRMSG_set")]
  public static extern void HDR_STRUCT_AS_B4C_ERRMSG_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_B4C_ERRMSG_get")]
  public static extern string HDR_STRUCT_AS_B4C_ERRMSG_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_bpb_set")]
  public static extern void HDR_STRUCT_AS_bpb_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_bpb_get")]
  public static extern uint HDR_STRUCT_AS_bpb_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_bpb8_set")]
  public static extern void HDR_STRUCT_AS_bpb8_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_bpb8_get")]
  public static extern uint HDR_STRUCT_AS_bpb8_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_Header_set")]
  public static extern void HDR_STRUCT_AS_Header_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_Header_get")]
  public static extern global::System.IntPtr HDR_STRUCT_AS_Header_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_rawEventData_set")]
  public static extern void HDR_STRUCT_AS_rawEventData_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_rawEventData_get")]
  public static extern global::System.IntPtr HDR_STRUCT_AS_rawEventData_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_rawdata_set")]
  public static extern void HDR_STRUCT_AS_rawdata_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_rawdata_get")]
  public static extern global::System.IntPtr HDR_STRUCT_AS_rawdata_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_first_set")]
  public static extern void HDR_STRUCT_AS_first_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_first_get")]
  public static extern uint HDR_STRUCT_AS_first_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_length_set")]
  public static extern void HDR_STRUCT_AS_length_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_length_get")]
  public static extern uint HDR_STRUCT_AS_length_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_auxBUF_set")]
  public static extern void HDR_STRUCT_AS_auxBUF_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_auxBUF_get")]
  public static extern global::System.IntPtr HDR_STRUCT_AS_auxBUF_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_bci2000_set")]
  public static extern void HDR_STRUCT_AS_bci2000_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_bci2000_get")]
  public static extern string HDR_STRUCT_AS_bci2000_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_fpulse_set")]
  public static extern void HDR_STRUCT_AS_fpulse_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_fpulse_get")]
  public static extern string HDR_STRUCT_AS_fpulse_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_stimfit_set")]
  public static extern void HDR_STRUCT_AS_stimfit_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_stimfit_get")]
  public static extern string HDR_STRUCT_AS_stimfit_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_SegSel_set")]
  public static extern void HDR_STRUCT_AS_SegSel_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_SegSel_get")]
  public static extern global::System.IntPtr HDR_STRUCT_AS_SegSel_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_B4C_ERRNUM_set")]
  public static extern void HDR_STRUCT_AS_B4C_ERRNUM_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_B4C_ERRNUM_get")]
  public static extern int HDR_STRUCT_AS_B4C_ERRNUM_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_flag_collapsed_rawdata_set")]
  public static extern void HDR_STRUCT_AS_flag_collapsed_rawdata_set(global::System.Runtime.InteropServices.HandleRef jarg1, char jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_AS_flag_collapsed_rawdata_get")]
  public static extern char HDR_STRUCT_AS_flag_collapsed_rawdata_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_new_HDR_STRUCT_AS")]
  public static extern global::System.IntPtr new_HDR_STRUCT_AS();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_delete_HDR_STRUCT_AS")]
  public static extern void delete_HDR_STRUCT_AS(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_gzFID_set")]
  public static extern void HDR_STRUCT_FILE_gzFID_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_gzFID_get")]
  public static extern global::System.IntPtr HDR_STRUCT_FILE_gzFID_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_FID_set")]
  public static extern void HDR_STRUCT_FILE_FID_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_FID_get")]
  public static extern global::System.IntPtr HDR_STRUCT_FILE_FID_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_size_set")]
  public static extern void HDR_STRUCT_FILE_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_size_get")]
  public static extern uint HDR_STRUCT_FILE_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_POS_set")]
  public static extern void HDR_STRUCT_FILE_POS_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_POS_get")]
  public static extern uint HDR_STRUCT_FILE_POS_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_Des_set")]
  public static extern void HDR_STRUCT_FILE_Des_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_Des_get")]
  public static extern int HDR_STRUCT_FILE_Des_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_DES_set")]
  public static extern void HDR_STRUCT_FILE_DES_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_DES_get")]
  public static extern int HDR_STRUCT_FILE_DES_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_OPEN_set")]
  public static extern void HDR_STRUCT_FILE_OPEN_set(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_OPEN_get")]
  public static extern byte HDR_STRUCT_FILE_OPEN_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_LittleEndian_set")]
  public static extern void HDR_STRUCT_FILE_LittleEndian_set(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_LittleEndian_get")]
  public static extern byte HDR_STRUCT_FILE_LittleEndian_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_COMPRESSION_set")]
  public static extern void HDR_STRUCT_FILE_COMPRESSION_set(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FILE_COMPRESSION_get")]
  public static extern byte HDR_STRUCT_FILE_COMPRESSION_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_new_HDR_STRUCT_FILE")]
  public static extern global::System.IntPtr new_HDR_STRUCT_FILE();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_delete_HDR_STRUCT_FILE")]
  public static extern void delete_HDR_STRUCT_FILE(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FLAG_OVERFLOWDETECTION_set")]
  public static extern void HDR_STRUCT_FLAG_OVERFLOWDETECTION_set(global::System.Runtime.InteropServices.HandleRef jarg1, char jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FLAG_OVERFLOWDETECTION_get")]
  public static extern char HDR_STRUCT_FLAG_OVERFLOWDETECTION_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FLAG_UCAL_set")]
  public static extern void HDR_STRUCT_FLAG_UCAL_set(global::System.Runtime.InteropServices.HandleRef jarg1, char jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FLAG_UCAL_get")]
  public static extern char HDR_STRUCT_FLAG_UCAL_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FLAG_ANONYMOUS_set")]
  public static extern void HDR_STRUCT_FLAG_ANONYMOUS_set(global::System.Runtime.InteropServices.HandleRef jarg1, char jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FLAG_ANONYMOUS_get")]
  public static extern char HDR_STRUCT_FLAG_ANONYMOUS_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FLAG_ROW_BASED_CHANNELS_set")]
  public static extern void HDR_STRUCT_FLAG_ROW_BASED_CHANNELS_set(global::System.Runtime.InteropServices.HandleRef jarg1, char jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FLAG_ROW_BASED_CHANNELS_get")]
  public static extern char HDR_STRUCT_FLAG_ROW_BASED_CHANNELS_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FLAG_TARGETSEGMENT_set")]
  public static extern void HDR_STRUCT_FLAG_TARGETSEGMENT_set(global::System.Runtime.InteropServices.HandleRef jarg1, char jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_FLAG_TARGETSEGMENT_get")]
  public static extern char HDR_STRUCT_FLAG_TARGETSEGMENT_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_new_HDR_STRUCT_FLAG")]
  public static extern global::System.IntPtr new_HDR_STRUCT_FLAG();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_delete_HDR_STRUCT_FLAG")]
  public static extern void delete_HDR_STRUCT_FLAG(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_SampleRate_set")]
  public static extern void HDR_STRUCT_EVENT_SampleRate_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_SampleRate_get")]
  public static extern double HDR_STRUCT_EVENT_SampleRate_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_TYP_set")]
  public static extern void HDR_STRUCT_EVENT_TYP_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_TYP_get")]
  public static extern global::System.IntPtr HDR_STRUCT_EVENT_TYP_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_POS_set")]
  public static extern void HDR_STRUCT_EVENT_POS_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_POS_get")]
  public static extern global::System.IntPtr HDR_STRUCT_EVENT_POS_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_DUR_set")]
  public static extern void HDR_STRUCT_EVENT_DUR_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_DUR_get")]
  public static extern global::System.IntPtr HDR_STRUCT_EVENT_DUR_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_CHN_set")]
  public static extern void HDR_STRUCT_EVENT_CHN_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_CHN_get")]
  public static extern global::System.IntPtr HDR_STRUCT_EVENT_CHN_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_TimeStamp_set")]
  public static extern void HDR_STRUCT_EVENT_TimeStamp_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_TimeStamp_get")]
  public static extern global::System.IntPtr HDR_STRUCT_EVENT_TimeStamp_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_CodeDesc_set")]
  public static extern void HDR_STRUCT_EVENT_CodeDesc_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_CodeDesc_get")]
  public static extern global::System.IntPtr HDR_STRUCT_EVENT_CodeDesc_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_N_set")]
  public static extern void HDR_STRUCT_EVENT_N_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_N_get")]
  public static extern uint HDR_STRUCT_EVENT_N_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_LenCodeDesc_set")]
  public static extern void HDR_STRUCT_EVENT_LenCodeDesc_set(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_EVENT_LenCodeDesc_get")]
  public static extern ushort HDR_STRUCT_EVENT_LenCodeDesc_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_new_HDR_STRUCT_EVENT")]
  public static extern global::System.IntPtr new_HDR_STRUCT_EVENT();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_delete_HDR_STRUCT_EVENT")]
  public static extern void delete_HDR_STRUCT_EVENT(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ELEC_REF_set")]
  public static extern void HDR_STRUCT_ELEC_REF_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ELEC_REF_get")]
  public static extern global::System.IntPtr HDR_STRUCT_ELEC_REF_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ELEC_GND_set")]
  public static extern void HDR_STRUCT_ELEC_GND_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ELEC_GND_get")]
  public static extern global::System.IntPtr HDR_STRUCT_ELEC_GND_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_new_HDR_STRUCT_ELEC")]
  public static extern global::System.IntPtr new_HDR_STRUCT_ELEC();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_delete_HDR_STRUCT_ELEC")]
  public static extern void delete_HDR_STRUCT_ELEC(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Recording_set")]
  public static extern void HDR_STRUCT_ID_Recording_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Recording_get")]
  public static extern string HDR_STRUCT_ID_Recording_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Technician_set")]
  public static extern void HDR_STRUCT_ID_Technician_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Technician_get")]
  public static extern string HDR_STRUCT_ID_Technician_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Hospital_set")]
  public static extern void HDR_STRUCT_ID_Hospital_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Hospital_get")]
  public static extern string HDR_STRUCT_ID_Hospital_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Equipment_set")]
  public static extern void HDR_STRUCT_ID_Equipment_set(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Equipment_get")]
  public static extern ulong HDR_STRUCT_ID_Equipment_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Manufacturer_get")]
  public static extern global::System.IntPtr HDR_STRUCT_ID_Manufacturer_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_new_HDR_STRUCT_ID")]
  public static extern global::System.IntPtr new_HDR_STRUCT_ID();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_delete_HDR_STRUCT_ID")]
  public static extern void delete_HDR_STRUCT_ID(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Manufacturer_Name_set")]
  public static extern void HDR_STRUCT_ID_Manufacturer_Name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Manufacturer_Name_get")]
  public static extern string HDR_STRUCT_ID_Manufacturer_Name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Manufacturer_Model_set")]
  public static extern void HDR_STRUCT_ID_Manufacturer_Model_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Manufacturer_Model_get")]
  public static extern string HDR_STRUCT_ID_Manufacturer_Model_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Manufacturer_Version_set")]
  public static extern void HDR_STRUCT_ID_Manufacturer_Version_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Manufacturer_Version_get")]
  public static extern string HDR_STRUCT_ID_Manufacturer_Version_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Manufacturer_SerialNumber_set")]
  public static extern void HDR_STRUCT_ID_Manufacturer_SerialNumber_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Manufacturer_SerialNumber_get")]
  public static extern string HDR_STRUCT_ID_Manufacturer_SerialNumber_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Manufacturer__field_set")]
  public static extern void HDR_STRUCT_ID_Manufacturer__field_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_ID_Manufacturer__field_get")]
  public static extern string HDR_STRUCT_ID_Manufacturer__field_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_new_HDR_STRUCT_ID_Manufacturer")]
  public static extern global::System.IntPtr new_HDR_STRUCT_ID_Manufacturer();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_delete_HDR_STRUCT_ID_Manufacturer")]
  public static extern void delete_HDR_STRUCT_ID_Manufacturer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Birthday_set")]
  public static extern void HDR_STRUCT_Patient_Birthday_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Birthday_get")]
  public static extern long HDR_STRUCT_Patient_Birthday_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Headsize_set")]
  public static extern void HDR_STRUCT_Patient_Headsize_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Headsize_get")]
  public static extern global::System.IntPtr HDR_STRUCT_Patient_Headsize_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Name_set")]
  public static extern void HDR_STRUCT_Patient_Name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Name_get")]
  public static extern string HDR_STRUCT_Patient_Name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Id_set")]
  public static extern void HDR_STRUCT_Patient_Id_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Id_get")]
  public static extern string HDR_STRUCT_Patient_Id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Weight_set")]
  public static extern void HDR_STRUCT_Patient_Weight_set(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Weight_get")]
  public static extern byte HDR_STRUCT_Patient_Weight_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Height_set")]
  public static extern void HDR_STRUCT_Patient_Height_set(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Height_get")]
  public static extern byte HDR_STRUCT_Patient_Height_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Sex_set")]
  public static extern void HDR_STRUCT_Patient_Sex_set(global::System.Runtime.InteropServices.HandleRef jarg1, sbyte jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Sex_get")]
  public static extern sbyte HDR_STRUCT_Patient_Sex_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Handedness_set")]
  public static extern void HDR_STRUCT_Patient_Handedness_set(global::System.Runtime.InteropServices.HandleRef jarg1, sbyte jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Handedness_get")]
  public static extern sbyte HDR_STRUCT_Patient_Handedness_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Smoking_set")]
  public static extern void HDR_STRUCT_Patient_Smoking_set(global::System.Runtime.InteropServices.HandleRef jarg1, sbyte jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Smoking_get")]
  public static extern sbyte HDR_STRUCT_Patient_Smoking_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_AlcoholAbuse_set")]
  public static extern void HDR_STRUCT_Patient_AlcoholAbuse_set(global::System.Runtime.InteropServices.HandleRef jarg1, sbyte jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_AlcoholAbuse_get")]
  public static extern sbyte HDR_STRUCT_Patient_AlcoholAbuse_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_DrugAbuse_set")]
  public static extern void HDR_STRUCT_Patient_DrugAbuse_set(global::System.Runtime.InteropServices.HandleRef jarg1, sbyte jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_DrugAbuse_get")]
  public static extern sbyte HDR_STRUCT_Patient_DrugAbuse_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Medication_set")]
  public static extern void HDR_STRUCT_Patient_Medication_set(global::System.Runtime.InteropServices.HandleRef jarg1, sbyte jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Medication_get")]
  public static extern sbyte HDR_STRUCT_Patient_Medication_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Impairment_get")]
  public static extern global::System.IntPtr HDR_STRUCT_Patient_Impairment_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_new_HDR_STRUCT_Patient")]
  public static extern global::System.IntPtr new_HDR_STRUCT_Patient();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_delete_HDR_STRUCT_Patient")]
  public static extern void delete_HDR_STRUCT_Patient(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Impairment_Visual_set")]
  public static extern void HDR_STRUCT_Patient_Impairment_Visual_set(global::System.Runtime.InteropServices.HandleRef jarg1, sbyte jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Impairment_Visual_get")]
  public static extern sbyte HDR_STRUCT_Patient_Impairment_Visual_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Impairment_Heart_set")]
  public static extern void HDR_STRUCT_Patient_Impairment_Heart_set(global::System.Runtime.InteropServices.HandleRef jarg1, sbyte jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_Patient_Impairment_Heart_get")]
  public static extern sbyte HDR_STRUCT_Patient_Impairment_Heart_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_new_HDR_STRUCT_Patient_Impairment")]
  public static extern global::System.IntPtr new_HDR_STRUCT_Patient_Impairment();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_delete_HDR_STRUCT_Patient_Impairment")]
  public static extern void delete_HDR_STRUCT_Patient_Impairment(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_data_size_set")]
  public static extern void HDR_STRUCT_data_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_data_size_get")]
  public static extern global::System.IntPtr HDR_STRUCT_data_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_data_block_set")]
  public static extern void HDR_STRUCT_data_block_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_HDR_STRUCT_data_block_get")]
  public static extern global::System.IntPtr HDR_STRUCT_data_block_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_new_HDR_STRUCT_data")]
  public static extern global::System.IntPtr new_HDR_STRUCT_data();

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_delete_HDR_STRUCT_data")]
  public static extern void delete_HDR_STRUCT_data(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_constructHDR")]
  public static extern global::System.IntPtr constructHDR(uint jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_destructHDR")]
  public static extern void destructHDR(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_sopen")]
  public static extern global::System.IntPtr sopen(string jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_sclose")]
  public static extern int sclose(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_sread")]
  public static extern uint sread([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.Out, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]double[] jarg1, uint jarg2, uint jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_swrite")]
  public static extern uint swrite([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.Out, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]double[] jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_seof")]
  public static extern int seof(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_srewind")]
  public static extern void srewind(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_sseek")]
  public static extern int sseek(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_stell")]
  public static extern int stell(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_serror2")]
  public static extern int serror2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_biosig_check_error")]
  public static extern int biosig_check_error(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_biosig_get_errormsg")]
  public static extern string biosig_get_errormsg(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_RerefCHANNEL")]
  public static extern int RerefCHANNEL(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, char jarg3);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_GetFileTypeString")]
  public static extern string GetFileTypeString(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_PhysDimCode")]
  public static extern ushort PhysDimCode(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_PhysDim3")]
  public static extern string PhysDim3(ushort jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_PhysDimScale")]
  public static extern double PhysDimScale(ushort jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_biosig_get_number_of_channels")]
  public static extern int biosig_get_number_of_channels(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("biosigWIN64.dll", EntryPoint="CSharp_BiosigLibWin64_biosig_get_channel")]
  public static extern global::System.IntPtr biosig_get_channel(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);
}

}
