//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BiosigLibWin64 {

public class HDR_STRUCT_SCP : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal HDR_STRUCT_SCP(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(HDR_STRUCT_SCP obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~HDR_STRUCT_SCP() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          biosigPINVOKE.delete_HDR_STRUCT_SCP(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_unsigned_char Section7 {
    set {
      biosigPINVOKE.HDR_STRUCT_SCP_Section7_set(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = biosigPINVOKE.HDR_STRUCT_SCP_Section7_get(swigCPtr);
      SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_char Section8 {
    set {
      biosigPINVOKE.HDR_STRUCT_SCP_Section8_set(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = biosigPINVOKE.HDR_STRUCT_SCP_Section8_get(swigCPtr);
      SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_char Section9 {
    set {
      biosigPINVOKE.HDR_STRUCT_SCP_Section9_set(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = biosigPINVOKE.HDR_STRUCT_SCP_Section9_get(swigCPtr);
      SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_char Section10 {
    set {
      biosigPINVOKE.HDR_STRUCT_SCP_Section10_set(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = biosigPINVOKE.HDR_STRUCT_SCP_Section10_get(swigCPtr);
      SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_char Section11 {
    set {
      biosigPINVOKE.HDR_STRUCT_SCP_Section11_set(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = biosigPINVOKE.HDR_STRUCT_SCP_Section11_get(swigCPtr);
      SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
      return ret;
    } 
  }

  public uint Section7Length {
    set {
      biosigPINVOKE.HDR_STRUCT_SCP_Section7Length_set(swigCPtr, value);
    } 
    get {
      uint ret = biosigPINVOKE.HDR_STRUCT_SCP_Section7Length_get(swigCPtr);
      return ret;
    } 
  }

  public uint Section8Length {
    set {
      biosigPINVOKE.HDR_STRUCT_SCP_Section8Length_set(swigCPtr, value);
    } 
    get {
      uint ret = biosigPINVOKE.HDR_STRUCT_SCP_Section8Length_get(swigCPtr);
      return ret;
    } 
  }

  public uint Section9Length {
    set {
      biosigPINVOKE.HDR_STRUCT_SCP_Section9Length_set(swigCPtr, value);
    } 
    get {
      uint ret = biosigPINVOKE.HDR_STRUCT_SCP_Section9Length_get(swigCPtr);
      return ret;
    } 
  }

  public uint Section10Length {
    set {
      biosigPINVOKE.HDR_STRUCT_SCP_Section10Length_set(swigCPtr, value);
    } 
    get {
      uint ret = biosigPINVOKE.HDR_STRUCT_SCP_Section10Length_get(swigCPtr);
      return ret;
    } 
  }

  public uint Section11Length {
    set {
      biosigPINVOKE.HDR_STRUCT_SCP_Section11Length_set(swigCPtr, value);
    } 
    get {
      uint ret = biosigPINVOKE.HDR_STRUCT_SCP_Section11Length_get(swigCPtr);
      return ret;
    } 
  }

  public HDR_STRUCT_SCP() : this(biosigPINVOKE.new_HDR_STRUCT_SCP(), true) {
  }

}

}
