//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BiosigLibWin64 {

public class HDR_STRUCT_EVENT : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal HDR_STRUCT_EVENT(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(HDR_STRUCT_EVENT obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~HDR_STRUCT_EVENT() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          biosigPINVOKE.delete_HDR_STRUCT_EVENT(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double SampleRate {
    set {
      biosigPINVOKE.HDR_STRUCT_EVENT_SampleRate_set(swigCPtr, value);
    } 
    get {
      double ret = biosigPINVOKE.HDR_STRUCT_EVENT_SampleRate_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_short TYP {
    set {
      biosigPINVOKE.HDR_STRUCT_EVENT_TYP_set(swigCPtr, SWIGTYPE_p_unsigned_short.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = biosigPINVOKE.HDR_STRUCT_EVENT_TYP_get(swigCPtr);
      SWIGTYPE_p_unsigned_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_int POS {
    set {
      biosigPINVOKE.HDR_STRUCT_EVENT_POS_set(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = biosigPINVOKE.HDR_STRUCT_EVENT_POS_get(swigCPtr);
      SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_int DUR {
    set {
      biosigPINVOKE.HDR_STRUCT_EVENT_DUR_set(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = biosigPINVOKE.HDR_STRUCT_EVENT_DUR_get(swigCPtr);
      SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_short CHN {
    set {
      biosigPINVOKE.HDR_STRUCT_EVENT_CHN_set(swigCPtr, SWIGTYPE_p_unsigned_short.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = biosigPINVOKE.HDR_STRUCT_EVENT_CHN_get(swigCPtr);
      SWIGTYPE_p_unsigned_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_long_long TimeStamp {
    set {
      biosigPINVOKE.HDR_STRUCT_EVENT_TimeStamp_set(swigCPtr, SWIGTYPE_p_long_long.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = biosigPINVOKE.HDR_STRUCT_EVENT_TimeStamp_get(swigCPtr);
      SWIGTYPE_p_long_long ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_long_long(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_char CodeDesc {
    set {
      biosigPINVOKE.HDR_STRUCT_EVENT_CodeDesc_set(swigCPtr, SWIGTYPE_p_p_char.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = biosigPINVOKE.HDR_STRUCT_EVENT_CodeDesc_get(swigCPtr);
      SWIGTYPE_p_p_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_char(cPtr, false);
      return ret;
    } 
  }

  public uint N {
    set {
      biosigPINVOKE.HDR_STRUCT_EVENT_N_set(swigCPtr, value);
    } 
    get {
      uint ret = biosigPINVOKE.HDR_STRUCT_EVENT_N_get(swigCPtr);
      return ret;
    } 
  }

  public ushort LenCodeDesc {
    set {
      biosigPINVOKE.HDR_STRUCT_EVENT_LenCodeDesc_set(swigCPtr, value);
    } 
    get {
      ushort ret = biosigPINVOKE.HDR_STRUCT_EVENT_LenCodeDesc_get(swigCPtr);
      return ret;
    } 
  }

  public HDR_STRUCT_EVENT() : this(biosigPINVOKE.new_HDR_STRUCT_EVENT(), true) {
  }

}

}
