//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BiosigLibWin64 {

public class HDR_STRUCT_Patient_Impairment : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal HDR_STRUCT_Patient_Impairment(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(HDR_STRUCT_Patient_Impairment obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~HDR_STRUCT_Patient_Impairment() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          biosigPINVOKE.delete_HDR_STRUCT_Patient_Impairment(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public sbyte Visual {
    set {
      biosigPINVOKE.HDR_STRUCT_Patient_Impairment_Visual_set(swigCPtr, value);
    } 
    get {
      sbyte ret = biosigPINVOKE.HDR_STRUCT_Patient_Impairment_Visual_get(swigCPtr);
      return ret;
    } 
  }

  public sbyte Heart {
    set {
      biosigPINVOKE.HDR_STRUCT_Patient_Impairment_Heart_set(swigCPtr, value);
    } 
    get {
      sbyte ret = biosigPINVOKE.HDR_STRUCT_Patient_Impairment_Heart_get(swigCPtr);
      return ret;
    } 
  }

  public HDR_STRUCT_Patient_Impairment() : this(biosigPINVOKE.new_HDR_STRUCT_Patient_Impairment(), true) {
  }

}

}
