//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BiosigLibWin64 {

public class HDR_STRUCT_ID : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal HDR_STRUCT_ID(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(HDR_STRUCT_ID obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~HDR_STRUCT_ID() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          biosigPINVOKE.delete_HDR_STRUCT_ID(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string Recording {
    set {
      biosigPINVOKE.HDR_STRUCT_ID_Recording_set(swigCPtr, value);
    } 
    get {
      string ret = biosigPINVOKE.HDR_STRUCT_ID_Recording_get(swigCPtr);
      return ret;
    } 
  }

  public string Technician {
    set {
      biosigPINVOKE.HDR_STRUCT_ID_Technician_set(swigCPtr, value);
    } 
    get {
      string ret = biosigPINVOKE.HDR_STRUCT_ID_Technician_get(swigCPtr);
      return ret;
    } 
  }

  public string Hospital {
    set {
      biosigPINVOKE.HDR_STRUCT_ID_Hospital_set(swigCPtr, value);
    } 
    get {
      string ret = biosigPINVOKE.HDR_STRUCT_ID_Hospital_get(swigCPtr);
      return ret;
    } 
  }

  public ulong Equipment {
    set {
      biosigPINVOKE.HDR_STRUCT_ID_Equipment_set(swigCPtr, value);
    } 
    get {
      ulong ret = biosigPINVOKE.HDR_STRUCT_ID_Equipment_get(swigCPtr);
      return ret;
    } 
  }

  public HDR_STRUCT_ID_Manufacturer Manufacturer {
    get {
      global::System.IntPtr cPtr = biosigPINVOKE.HDR_STRUCT_ID_Manufacturer_get(swigCPtr);
      HDR_STRUCT_ID_Manufacturer ret = (cPtr == global::System.IntPtr.Zero) ? null : new HDR_STRUCT_ID_Manufacturer(cPtr, false);
      return ret;
    } 
  }

  public HDR_STRUCT_ID() : this(biosigPINVOKE.new_HDR_STRUCT_ID(), true) {
  }

}

}
