//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BiosigLibWin64 {

public class HDR_STRUCT_ID_Manufacturer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal HDR_STRUCT_ID_Manufacturer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(HDR_STRUCT_ID_Manufacturer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~HDR_STRUCT_ID_Manufacturer() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          biosigPINVOKE.delete_HDR_STRUCT_ID_Manufacturer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string Name {
    set {
      biosigPINVOKE.HDR_STRUCT_ID_Manufacturer_Name_set(swigCPtr, value);
    } 
    get {
      string ret = biosigPINVOKE.HDR_STRUCT_ID_Manufacturer_Name_get(swigCPtr);
      return ret;
    } 
  }

  public string Model {
    set {
      biosigPINVOKE.HDR_STRUCT_ID_Manufacturer_Model_set(swigCPtr, value);
    } 
    get {
      string ret = biosigPINVOKE.HDR_STRUCT_ID_Manufacturer_Model_get(swigCPtr);
      return ret;
    } 
  }

  public string Version {
    set {
      biosigPINVOKE.HDR_STRUCT_ID_Manufacturer_Version_set(swigCPtr, value);
    } 
    get {
      string ret = biosigPINVOKE.HDR_STRUCT_ID_Manufacturer_Version_get(swigCPtr);
      return ret;
    } 
  }

  public string SerialNumber {
    set {
      biosigPINVOKE.HDR_STRUCT_ID_Manufacturer_SerialNumber_set(swigCPtr, value);
    } 
    get {
      string ret = biosigPINVOKE.HDR_STRUCT_ID_Manufacturer_SerialNumber_get(swigCPtr);
      return ret;
    } 
  }

  public string _field {
    set {
      biosigPINVOKE.HDR_STRUCT_ID_Manufacturer__field_set(swigCPtr, value);
    } 
    get {
      string ret = biosigPINVOKE.HDR_STRUCT_ID_Manufacturer__field_get(swigCPtr);
      return ret;
    } 
  }

  public HDR_STRUCT_ID_Manufacturer() : this(biosigPINVOKE.new_HDR_STRUCT_ID_Manufacturer(), true) {
  }

}

}
