//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BiosigLibWin64 {

public class HDR_STRUCT_FLAG : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal HDR_STRUCT_FLAG(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(HDR_STRUCT_FLAG obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~HDR_STRUCT_FLAG() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          biosigPINVOKE.delete_HDR_STRUCT_FLAG(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public char OVERFLOWDETECTION {
    set {
      biosigPINVOKE.HDR_STRUCT_FLAG_OVERFLOWDETECTION_set(swigCPtr, value);
    } 
    get {
      char ret = biosigPINVOKE.HDR_STRUCT_FLAG_OVERFLOWDETECTION_get(swigCPtr);
      return ret;
    } 
  }

  public char UCAL {
    set {
      biosigPINVOKE.HDR_STRUCT_FLAG_UCAL_set(swigCPtr, value);
    } 
    get {
      char ret = biosigPINVOKE.HDR_STRUCT_FLAG_UCAL_get(swigCPtr);
      return ret;
    } 
  }

  public char ANONYMOUS {
    set {
      biosigPINVOKE.HDR_STRUCT_FLAG_ANONYMOUS_set(swigCPtr, value);
    } 
    get {
      char ret = biosigPINVOKE.HDR_STRUCT_FLAG_ANONYMOUS_get(swigCPtr);
      return ret;
    } 
  }

  public char ROW_BASED_CHANNELS {
    set {
      biosigPINVOKE.HDR_STRUCT_FLAG_ROW_BASED_CHANNELS_set(swigCPtr, value);
    } 
    get {
      char ret = biosigPINVOKE.HDR_STRUCT_FLAG_ROW_BASED_CHANNELS_get(swigCPtr);
      return ret;
    } 
  }

  public char TARGETSEGMENT {
    set {
      biosigPINVOKE.HDR_STRUCT_FLAG_TARGETSEGMENT_set(swigCPtr, value);
    } 
    get {
      char ret = biosigPINVOKE.HDR_STRUCT_FLAG_TARGETSEGMENT_get(swigCPtr);
      return ret;
    } 
  }

  public HDR_STRUCT_FLAG() : this(biosigPINVOKE.new_HDR_STRUCT_FLAG(), true) {
  }

}

}
